services:
  image-postgres-old:
    image: postgres:10.5-alpine
    container_name: image-postgres-old
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./dockerdata/postgres/10/data:/var/lib/postgresql/data/pgdata
    networks:
      - imagenet
