# Generated by Django 2.0.6 on 2018-06-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_auto_20180618_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='picture',
            field=models.ImageField(blank=True, max_length=127, upload_to='artworks/original/'),
        ),
    ]
