# Generated by Django 2.1 on 2018-10-08 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_auto_20181008_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='dateFromYear',
            new_name='dateYearFrom',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='dateToYear',
            new_name='dateYearTo',
        ),
    ]
