# Generated by Django 2.1 on 2018-10-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_auto_20181008_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='dateFrom',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='dateTo',
        ),
        migrations.AddField(
            model_name='artwork',
            name='titleEnglish',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='date',
            field=models.CharField(blank=True, help_text='1921-1923, 1917/1964, -20000, 2.Jh. - 4.Jh., Ende 14. Jh., 5.3.1799, um 1700', max_length=255),
        ),
    ]
