# Generated by Django 2.0.6 on 2018-06-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_artwork_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='picture',
            new_name='original',
        ),
    ]
