# Generated by Django 2.0.6 on 2018-06-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_auto_20180619_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='credits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='dimensions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='locationOfCreation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
