# Generated by Django 2.0.6 on 2018-06-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0005_auto_20180620_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
