# Generated by Django 2.0.6 on 2018-10-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_auto_20181016_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='material',
            field=models.TextField(blank=True, null=True),
        ),
    ]
