# Generated by Django 2.0.6 on 2018-06-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_auto_20180621_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='credits',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='dimensions',
            field=models.CharField(blank=True, default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='locationOfCreation',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='material',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
