# Generated by Django 2.0.6 on 2018-11-03 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0008_artwork_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
