# Generated by Django 2.0.6 on 2018-07-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0008_auto_20180626_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='dateFrom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='dateTo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
