# Generated by Django 2.0.6 on 2018-07-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0009_auto_20180702_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='surname',
        ),
    ]
