# Generated by Django 2.0.6 on 2018-08-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0010_auto_20180717_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='original',
        ),
        migrations.AddField(
            model_name='artwork',
            name='originalImage',
            field=models.ImageField(blank=True, max_length=127, upload_to='artworks/imageOriginal/'),
        ),
    ]
