# Generated by Django 2.0.6 on 2018-11-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0010_auto_20181103_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='locationOfCreation',
        ),
    ]
