# Generated by Django 2.0.6 on 2018-08-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0011_auto_20180809_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='originalImage',
            new_name='imageOriginal',
        ),
    ]
