# Generated by Django 2.0.6 on 2018-08-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0012_auto_20180809_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='locationOfCreation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
