# Generated by Django 2.0.6 on 2018-08-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0013_auto_20180809_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
