# Generated by Django 2.0.6 on 2018-08-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0014_auto_20180809_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='fileID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
