# Generated by Django 2.0.6 on 2018-11-08 13:30

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0015_artwork_locationofcreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='locationOfCreation',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.Location'),
        ),
    ]
