# Generated by Django 2.1 on 2018-08-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0016_remove_artwork_fileid'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='synonyms',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='imageOriginal',
            field=models.ImageField(blank=True, max_length=127, upload_to=''),
        ),
    ]
