# Generated by Django 2.0.6 on 2018-11-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0017_auto_20181124_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionartworkthroughmodel',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='collectionartworkthroughmodel',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='artworkcollection',
            name='artworks',
        ),
        migrations.AddField(
            model_name='artworkcollection',
            name='artworks',
            field=models.ManyToManyField(blank=True, to='artworks.Artwork'),
        ),
        migrations.DeleteModel(
            name='CollectionArtworkThroughModel',
        ),
    ]
