# Generated by Django 2.1 on 2018-08-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0017_auto_20180816_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artist',
        ),
        migrations.AddField(
            model_name='artwork',
            name='artists',
            field=models.ManyToManyField(to='artworks.Artist'),
        ),
    ]
