# Generated by Django 2.1 on 2018-08-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0018_auto_20180820_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artists',
            field=models.ManyToManyField(blank=True, to='artworks.Artist'),
        ),
    ]
