# Generated by Django 2.0.6 on 2018-11-24 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0018_auto_20181124_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkCollectionArtworkThroughModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.Artwork')),
            ],
            options={
                'ordering': ('collection', 'order'),
            },
        ),
        migrations.RemoveField(
            model_name='artworkcollection',
            name='artworks',
        ),
        migrations.AddField(
            model_name='artworkcollection',
            name='artworks',
            field=models.ManyToManyField(through='artworks.ArtworkCollectionArtworkThroughModel', to='artworks.Artwork'),
        ),
        migrations.AddField(
            model_name='artworkcollectionartworkthroughmodel',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.ArtworkCollection'),
        ),
    ]
