# Generated by Django 2.1 on 2018-08-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0019_auto_20180829_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='locationOfCreation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
