# Generated by Django 2.1 on 2018-08-30 16:56

import artworks.models
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0020_auto_20180830_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='imageOriginal',
            field=versatileimagefield.fields.VersatileImageField(blank=True, max_length=127, upload_to=artworks.models.get_path_to_original_file),
        ),
    ]
