# Generated by Django 2.0.6 on 2019-01-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0023_auto_20181216_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artworkcollection',
            options={'permissions': (('can_download_pptx', 'Download as PowerPoint file'),)},
        ),
    ]
