# Generated by Django 2.0.6 on 2019-01-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0024_auto_20190105_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artworkcollection',
            options={'permissions': (('can_download_pptx', 'Can download as PowerPoint file'),)},
        ),
        migrations.AddField(
            model_name='artworkcollectionmembership',
            name='needsOwnSlide',
            field=models.BooleanField(default=False),
        ),
    ]
