# Generated by Django 2.0.6 on 2019-01-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0028_auto_20190126_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='artworkcollection',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='artworkcollection',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
