# Generated by Django 2.0.6 on 2019-02-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0035_auto_20190217_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='artworks.Keyword', verbose_name='Keywords'),
        ),
    ]
