# Generated by Django 2.0.6 on 2019-03-12 09:49
from django.conf import settings
from django.contrib.auth.management import create_permissions
from django.db import migrations


def apply_migration(apps, schema_editor):
    # create permissions
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    group, created = Group.objects.get_or_create(name='editor')
    if created:
        perms = Permission.objects.filter(
            codename__in=[
                'add_artist',
                'change_artist',
                'delete_artist',
                'add_artwork',
                'change_artwork',
                'delete_artwork',
                'add_artworkcollection',
                'change_artworkcollection',
                'delete_artworkcollection',
                'can_download_pptx',
                'add_artworkcollectionmembership',
                'change_artworkcollectionmembership',
                'delete_artworkcollectionmembership',
                'add_keyword',
                'change_keyword',
                'delete_keyword',
                'add_location',
                'change_location',
                'delete_location',
            ]
        )
        group.permissions.set(perms)
        group.save()


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='editor').delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artworks', '0036_auto_20190217_1910'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration),
    ]
