# Generated by Django 2.2.1 on 2023-05-03 09:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0041_auto_20230406_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slides',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Slides'),
        ),
    ]
