    # Generated by Django 2.2.1 on 2023-06-28 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artworks', '0042_album_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='shared_info',
            field=models.ManyToManyField(related_name='shared_info_album', to=settings.AUTH_USER_MODEL, verbose_name='Shared Info'),
        ),
    ]
