# Generated by Django 2.2.28 on 2023-08-30 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artworks', '0045_auto_20230830_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='permissions',
            field=models.ManyToManyField(related_name='permissions', through='artworks.PermissionsRelation', to=settings.AUTH_USER_MODEL, verbose_name='Permissions'),
        ),
    ]
