# Generated by Django 4.2.6 on 2023-11-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0049_alter_albummembership_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artists',
            field=models.ManyToManyField(blank=True, to='artworks.artist', verbose_name='Artist'),
        ),
    ]
