# Generated by Django 4.2.6 on 2023-11-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0050_alter_artwork_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artists',
            field=models.ManyToManyField(blank=True, to='artworks.artist', verbose_name='Artists'),
        ),
    ]
