# Generated by Django 4.2.6 on 2024-02-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0052_alter_albummembership_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='location_current',
            new_name='location',
        ),
    ]
