# Generated by Django 4.2.6 on 2024-02-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0053_rename_location_current_artwork_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slides',
            field=models.JSONField(default=list, verbose_name='Slides'),
        ),
    ]
