# Generated by Django 4.2.6 on 2024-03-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0057_folder_alter_album_artworks_folderalbumrelation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artworks',
        ),
        migrations.DeleteModel(
            name='AlbumMembership',
        ),
    ]
