# Generated by Django 4.2.6 on 2024-03-20 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0059_alter_folder_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'managed': False, 'permissions': (('can_download_pptx', 'Can download as PowerPoint file'),), 'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
    ]
