# Generated by Django 4.2.6 on 2024-05-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0064_discriminatoryterm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='description',
            new_name='comments',
        ),
    ]
