# Generated by Django 4.2.15 on 2024-09-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_folders',
            field=models.CharField(choices=[('list', 'list'), ('grid', 'grid')], default='list'),
        ),
        migrations.AddField(
            model_name='user',
            name='display_images',
            field=models.CharField(choices=[('crop', 'crop'), ('resize', 'resize')], default='crop'),
        ),
    ]
