# Generated by Django 2.0.6 on 2018-10-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0007_auto_20181016_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='artworks.Keyword'),
        ),
    ]
