# Generated by Django 2.0.6 on 2018-11-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0009_auto_20181103_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artworkcollection',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='artworkcollection',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
