# Generated by Django 2.0.6 on 2018-11-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0012_auto_20181108_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='synonyms',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
