# Generated by Django 2.0.6 on 2018-11-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0013_auto_20181108_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='locationOfCreation',
        ),
    ]
