# Generated by Django 2.0.6 on 2018-11-08 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0014_remove_artwork_locationofcreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='locationOfCreation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.Location'),
        ),
    ]
