# Generated by Django 2.0.6 on 2018-11-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0019_auto_20181124_1438'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtworkCollectionArtworkThroughModel',
            new_name='ArtworkCollectionMembership',
        ),
    ]
