# Generated by Django 2.0.6 on 2018-12-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0021_auto_20181216_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
