# Generated by Django 2.0.6 on 2019-01-20 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0025_auto_20190119_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkcollectionmembership',
            name='connectedWith',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artworks.ArtworkCollectionMembership'),
        ),
    ]
