# Generated by Django 2.0.6 on 2019-01-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0026_artworkcollectionmembership_connectedwith'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworkcollectionmembership',
            name='needsOwnSlide',
        ),
        migrations.AddField(
            model_name='artwork',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
