# Generated by Django 2.0.6 on 2019-01-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0030_auto_20190126_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='dateYearFrom',
            new_name='date_year_from',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='dateYearTo',
            new_name='date_year_to',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='imageOriginal',
            new_name='image_original',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='locationOfCreation',
            new_name='location_of_creation',
        ),
    ]
