# Generated by Django 2.2.1 on 2021-03-29 09:39

import artworks.models
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0039_auto_20190325_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image_original',
            field=versatileimagefield.fields.VersatileImageField(blank=True, max_length=255, upload_to=artworks.models.get_path_to_original_file, verbose_name='Original Image'),
        ),
    ]
