# Generated by Django 4.2.6 on 2024-01-30 15:44
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0048_auto_20230928_1311'),
    ]

    operations = [
        TrigramExtension(),
    ]
