# Generated by Django 4.2.6 on 2024-02-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0050_auto_20240209_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='location_of_creation',
            new_name='place_of_production',
        ),
    ]
