# Generated by Django 4.2.6 on 2024-02-12 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0051_auto_20240212_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albummembership',
            options={'ordering': ('order',), 'verbose_name': 'Album Membership', 'verbose_name_plural': 'Album Memberships'},
        ),
        migrations.AlterField(
            model_name='albummembership',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.album', verbose_name='Album'),
        ),
    ]
