# Generated by Django 4.2.6 on 2024-02-13 10:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artworks', '0054_alter_album_slides'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permissionsrelation',
            unique_together={('album', 'user')},
        ),
    ]
