# Generated by Django 4.2.6 on 2024-02-20 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artworks', '0056_alter_permissionsrelation_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=22, prefix='', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'ordering': ('-date_created',),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='album',
            name='artworks',
            field=models.ManyToManyField(related_name='artwork_to_artworks', through='artworks.AlbumMembership', to='artworks.artwork', verbose_name='Artworks'),
        ),
        migrations.CreateModel(
            name='FolderAlbumRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_album', to='artworks.album')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_folder', to='artworks.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='albums',
            field=models.ManyToManyField(related_name='folder_to_albums', through='artworks.FolderAlbumRelation', to='artworks.album', verbose_name='Albums'),
        ),
        migrations.AddField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_owner', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_to_parent', to='artworks.folder'),
        ),
    ]
