# Generated by Django 4.2.6 on 2024-03-06 11:26

import base_common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0058_remove_album_artworks_delete_albummembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=base_common.fields.ShortUUIDField(primary_key=True, serialize=False),
        ),
    ]
