# Generated by Django 4.2.6 on 2024-04-26 06:03

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.contrib.postgres.aggregates import StringAgg
from django.contrib.postgres.search import SearchVector
from django.db import migrations
from django.db.models import Value


def update_search_vector(apps, schema_editor):
    Artwork = apps.get_model("artworks", "Artwork")
    search_vector = (
            SearchVector('title', weight='A')
            + SearchVector('title_english', weight='A')
            + SearchVector(Value('artists_names'), weight='A')
            + SearchVector(Value('artists_synonyms'), weight='A')
            + SearchVector('description', weight='B')
            + SearchVector(Value('keywords_names'), weight='B')
            + SearchVector(Value('place_of_production_names'), weight='B')
            + SearchVector(Value('place_of_production_synonyms'), weight='B')
            + SearchVector(Value('location_names'), weight='B')
            + SearchVector(Value('location_synonyms'), weight='B')
            + SearchVector('credits', weight='C')
            + SearchVector('material', weight='C')
            + SearchVector('dimensions', weight='C')
            + SearchVector('date', weight='C')
    )

    Artwork.objects.all().annotate(
        artists_names=StringAgg('artists__name', delimiter=' ')
    ).annotate(
        artists_synonyms=StringAgg('artists__synonyms', delimiter=' ')
    ).annotate(
        keywords_names=StringAgg('keywords__name', delimiter=' ')
    ).annotate(
        place_of_production_names=StringAgg('place_of_production__name', delimiter=' ')
    ).annotate(
        place_of_production_synonyms=StringAgg('place_of_production__synonyms', delimiter=' ')
    ).annotate(
        location_names=StringAgg('location__name', delimiter=' ')
    ).annotate(
        location_synonyms=StringAgg('location__synonyms', delimiter=' ')
    ).update(search_vector=search_vector)


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0062_alter_album_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='artworks_ar_search__9a85c2_gin'),
        ),
        migrations.RunPython(
            update_search_vector,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
