# Generated by Django 4.2.6 on 2024-05-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0068_album_last_changed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='title_comment',
            field=models.TextField(blank=True, verbose_name='Comment on title'),
        ),
    ]
