# Generated by Django 4.2.6 on 2024-06-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0069_artwork_title_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='date_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='external_metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='gnd_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
