# Generated by Django 4.2.6 on 2024-06-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0071_artist_date_birth_artist_date_death_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='synonyms',
            field=models.CharField(blank=True, help_text='Comma-separated list of synonyms.', verbose_name='Synonyms'),
        ),
    ]
