# Generated by Django 4.2.6 on 2024-07-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0073_artist_gnd_overwrite'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='date_display',
            field=models.CharField(blank=True, help_text='Overrides birth and death dates for display, if not empty.', null=True),
        ),
    ]
