# Generated by Django 4.2.6 on 2024-07-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0074_artist_date_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='gnd_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
