# Generated by Django 4.2.13 on 2024-07-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0075_alter_artist_gnd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='external_metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='gnd_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='location',
            name='gnd_overwrite',
            field=models.BooleanField(default=True, help_text='Overwrite entry with data from GND?'),
        ),
    ]
