# Generated by Django 4.2.13 on 2024-07-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0076_location_gnd_id_location_gnd_overwrite'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='external_metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
