# Generated by Django 4.2.13 on 2024-07-16 13:05

from django.db import migrations, models

def shorten_synonyms(apps, schema_editor):
    Location = apps.get_model("artworks", "Location")
    for location in Location.objects.all():
        if len(location.synonyms) > 255:
            location.synonyms = location.synonyms[:255]
            location.save()

class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0076_alter_location_gnd_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='synonyms',
            field=models.CharField(blank=True, verbose_name='Synonyms'),
        ),
        migrations.RunPython(code=migrations.RunPython.noop, reverse_code=shorten_synonyms)
    ]
