# Generated by Django 4.2.13 on 2024-07-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0077_location_external_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
