# Generated by Django 4.2.13 on 2024-07-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0077_alter_location_synonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='external_metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='getty_overwrite',
            field=models.BooleanField(default=True, help_text='Overwrite Name, English with data from Getty AAT?'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='getty_id',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True, verbose_name='Getty AAT ID'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name, English'),
        ),
    ]
