# Generated by Django 4.2.13 on 2024-07-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0078_location_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name, English'),
        ),
    ]
