# Generated by Django 4.2.13 on 2024-07-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0078_location_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='synonyms_location',
            field=models.CharField(blank=True, help_text='Comma-separated list of synonyms.', verbose_name='Synonyms_Location'),
        ),
    ]
