# Generated by Django 4.2.13 on 2024-07-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0078_keyword_external_metadata_keyword_getty_overwrite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='getty_url',
        ),
        migrations.AddField(
            model_name='keyword',
            name='getty_id',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True, verbose_name='Getty AAT ID'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='getty_overwrite',
            field=models.BooleanField(default=True, help_text='Overwrite entry of Name, English with data from Getty?'),
        ),
    ]
