# Generated by Django 4.2.13 on 2024-08-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0079_location_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='discriminatory_terms',
            field=models.ManyToManyField(to='artworks.discriminatoryterm', verbose_name='Discriminatory terms'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artists',
            field=models.ManyToManyField(to='artworks.artist', verbose_name='Artists'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='keywords',
            field=models.ManyToManyField(to='artworks.keyword', verbose_name='Keywords'),
        ),
    ]
