# Generated by Django 4.2.13 on 2024-08-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0079_location_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='discriminatory_terms',
            field=models.ManyToManyField(blank=True, to='artworks.discriminatoryterm', verbose_name='Discriminatory terms'),
        ),
    ]
