# Generated by Django 4.2.15 on 2024-08-13 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0080_artwork_discriminatory_terms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='Person',
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name'], 'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
    ]
