# Generated by Django 4.2.15 on 2024-08-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0081_rename_artist_person_alter_person_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='gnd_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='GND ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gnd_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='GND ID'),
        ),
    ]
