# Generated by Django 4.2.15 on 2024-08-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0082_alter_location_gnd_id_alter_person_gnd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to='artworks.person', verbose_name='Authors'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='graphic_designers',
            field=models.ManyToManyField(related_name='graphic_designers', to='artworks.person', verbose_name='Graphic designers'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='photographers',
            field=models.ManyToManyField(related_name='photographers', to='artworks.person', verbose_name='Photographers'),
        ),
    ]
