# Generated by Django 4.2.15 on 2024-08-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0083_artwork_authors_artwork_graphic_designers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='link',
            field=models.URLField(blank=True, verbose_name='Link'),
        ),
    ]
