# Generated by Django 4.2.15 on 2024-10-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0084_alter_artwork_material_old_alter_person_date_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='place_of_production_new',
            field=models.ManyToManyField(blank=True, related_name='artworks_created_here_new', to='artworks.location', verbose_name='Place of Production'),
        ),
    ]
