# Generated by Django 4.2.15 on 2024-08-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0084_artwork_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='credits',
            new_name='publication',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='publication',
            field=models.TextField(blank=True, verbose_name='Publication title'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='publication_isbn',
            field=models.CharField(blank=True, verbose_name='Publication ISBN'),
        ),
    ]
