# Generated by Django 4.2.15 on 2024-08-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0085_rename_credits_artwork_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='dimensions',
            new_name='dimensions_freetext',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='dimensions_freetext',
            field=models.CharField(
                blank=True,
                help_text='Free text, can be used to overrule width x height x depth',
                max_length=255,
                verbose_name='Dimensions'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='depth',
            field=models.FloatField(blank=True, null=True, verbose_name='Depth'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='Width'),
        ),
    ]
