# Generated by Django 4.2.15 on 2024-10-01 11:46

from django.db import migrations

def migrate_fk_to_m2m(apps, schema_editor):
    Artwork = apps.get_model('artworks', 'Artwork')

    for artwork in Artwork.objects.all():
        if artwork.place_of_production:
            artwork.place_of_production_new.add(artwork.place_of_production)

class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0085_artwork_place_of_production_new'),
    ]

    operations = [
        migrations.RunPython(migrate_fk_to_m2m),
    ]
