# Generated by Django 4.2.15 on 2024-10-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0086_migrate_fk_to_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='place_of_production_new',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='place_of_production',
        ),
        migrations.AddField(
            model_name='artwork',
            name='place_of_production',
            field=models.ManyToManyField(blank=True, related_name='artworks_created_here', to='artworks.location', verbose_name='Place of Production'),
        ),
    ]
