# Generated by Django 4.2.15 on 2024-08-22 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0086_rename_artwork_dimensions_artwork_depth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(verbose_name='Material/Technique')),
                ('name_en', models.TextField(blank=True, default='', verbose_name='Material/Technique, English')),
            ],
            options={
                'ordering': ('-date_created',),
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='material',
            new_name='material_old',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='material_old',
            field=models.TextField(
                blank=True,
                null=True,
                help_text='Deprecated. Used only if material is not chosen.',
                verbose_name='Material/Technique (old)',
            ),
        ),
        migrations.AddField(
            model_name='artwork',
            name='material',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='artworks.material',
                verbose_name='Material/Technique',
            ),
        ),
    ]
