# Generated by Django 4.2.16 on 2024-10-18 09:55
from django.db import migrations, models
import django_jsonform.models.fields

SEPARATOR = ', '


def migrate_synonyms(apps, schema_editor):
    Person = apps.get_model("artworks", "Person")
    Location = apps.get_model("artworks", "Location")

    for qs in [Person.objects.all(), Location.objects.all()]:
        for instance in qs:
            instance.synonyms = [i.strip() for i in instance.synonyms_old.split(SEPARATOR)]
            instance.save()

def migrate_synonyms_reverse(apps, schema_editor):
    Person = apps.get_model("artworks", "Person")
    Location = apps.get_model("artworks", "Location")

    for qs in [Person.objects.all(), Location.objects.all()]:
        for instance in qs:
            instance.synonyms_old = SEPARATOR.join(instance.synonyms)
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0088_alter_artwork_place_of_production'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='synonyms',
            new_name='synonyms_old',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='synonyms',
            new_name='synonyms_old',
        ),
        migrations.AlterField(
            model_name='location',
            name='synonyms_old',
            field=models.CharField(blank=True, verbose_name='Synonyms (old)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='synonyms_old',
            field=models.CharField(blank=True, verbose_name='Synonyms (old)'),
        ),
        migrations.AddField(
            model_name='location',
            name='synonyms',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(), default=list, size=None, verbose_name='Synonyms'),
        ),
        migrations.AddField(
            model_name='person',
            name='synonyms',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(), default=list, size=None, verbose_name='Synonyms'),
        ),
        migrations.RunPython(migrate_synonyms, reverse_code=migrate_synonyms_reverse),
    ]
