# Generated by Django 4.2.16 on 2024-10-18 12:41
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0089_rename_synonyms_location_synonyms_old_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='search_keywords',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='artwork',
            name='search_locations',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='artwork',
            name='search_materials',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='artwork',
            name='search_persons',
            field=models.CharField(blank=True, default=''),
        ),
    ]
