# Generated by Django 4.2.15 on 2024-10-25 13:00
import logging
from django.db import migrations
import versatileimagefield.fields
import artworks.models

logger = logging.getLogger(__name__)

def create_fullsize_images(apps, schema_editor):
    from artworks.models import Artwork
    for artwork in Artwork.objects.all():
        if hasattr(artwork, 'create_image_fullsize') and callable(artwork.create_image_fullsize):
            artwork.create_image_fullsize()
        else:
            logger.warning('Artwork model does\'n have a create_image_fullsize method [artworks migration 0091]')
            break

class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0090_artwork_search_keywords_artwork_search_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image_fullsize',
            field=versatileimagefield.fields.VersatileImageField(blank=True, max_length=255, null=False, upload_to=artworks.models.get_path_to_image_fullsize, verbose_name='Fullsize Image'),
        ),
        migrations.RunPython(
            create_fullsize_images,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
