# Generated by Django 4.2.16 on 2024-11-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0090_artwork_search_keywords_artwork_search_locations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='material_old',
            new_name='material_description',
        ),
    ]
