# Generated by Django 4.2.15 on 2024-10-25 13:00

from django.db import migrations
import versatileimagefield.fields
import artworks.models



class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0090_artwork_search_keywords_artwork_search_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image_fullsize',
            field=versatileimagefield.fields.VersatileImageField(blank=True, max_length=255, null=False, upload_to=artworks.models.get_path_to_image_fullsize, verbose_name='Fullsize Image'),
        ),
    ]
