# Generated by Django 4.2.15 on 2024-10-23 10:22
from dataclasses import field

import artworks.models
from django.db import migrations
import functools
import os
import versatileimagefield.fields

from artworks.models import convert_to_fullsize_image


def convert_images_to_jpeg(apps, schema_editor):
    """Populate image_fullsize by converting current images, saved under image_original, to the default JPEG format"""
    Artwork = apps.get_model('artworks', 'Artwork')
    for artwork in Artwork.objects.all():
        image_original_path = artwork.image_original.path
        if image_original_path and os.path.exists(image_original_path):
            convert_to_fullsize_image(instance=artwork, path=image_original_path)
            artwork.save()

class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0090_artwork_search_keywords_artwork_search_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image_fullsize',
            field=versatileimagefield.fields.VersatileImageField(blank=True, max_length=255, null=False, upload_to=functools.partial(artworks.models.get_path_to_image_fullsize, *(),), verbose_name='Fullsize Image'),
        ),
        migrations.RunPython(
            convert_images_to_jpeg,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
