# Generated by Django 4.2.16 on 2024-11-06 17:29

import artworks.models
import artworks.validators
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0092_artwork_image_fullsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image_original',
            field=versatileimagefield.fields.VersatileImageField(blank=True, max_length=255, upload_to=artworks.models.get_path_to_original_file, validators=[artworks.validators.validate_image_original], verbose_name='Original Image'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='material_description',
            field=models.TextField(blank=True, help_text='Description of artwork materials and composition.', verbose_name='Material/Technique description'),
        ),
    ]
