# Generated by Django 4.2.16 on 2024-11-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0093_alter_artwork_image_original_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
    ]
