# Generated by Django 4.2.16 on 2024-11-07 18:10

import base_common.fields
from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0096_alter_artwork_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='archive_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='id',
            field=base_common.fields.ShortUUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': [django.db.models.functions.text.Upper('title')], 'verbose_name': 'Artwork', 'verbose_name_plural': 'Artworks'},
        ),
    ]
