# Generated by Django 4.2.16 on 2024-11-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0098_alter_album_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='comments',
            new_name='comments_de',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='material_description',
            new_name='material_description_de',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='title_comment',
            new_name='title_comment_de',
        ),
        migrations.AddField(
            model_name='artwork',
            name='comments_en',
            field=models.TextField(blank=True, verbose_name='Comments (EN)'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='material_description_en',
            field=models.TextField(
                blank=True,
                help_text='Description of artwork materials and composition.',
                verbose_name='Material/Technique description (EN)',
            ),
        ),
        migrations.AddField(
            model_name='artwork',
            name='title_comment_en',
            field=models.TextField(blank=True, verbose_name='Comment on title (EN)'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='comments_de',
            field=models.TextField(blank=True, verbose_name='Comments (DE)'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='material_description_de',
            field=models.TextField(
                blank=True,
                help_text='Description of artwork materials and composition.',
                verbose_name='Material/Technique description (DE)',
            ),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title_comment_de',
            field=models.TextField(blank=True, verbose_name='Comment on title (DE)'),
        ),
    ]
