# Generated by Django 4.2.16 on 2024-11-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0099_remove_artwork_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name (DE)'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name (EN)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name (DE)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name (EN)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.TextField(verbose_name='Material/Technique (DE)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name_en',
            field=models.TextField(blank=True, default='', verbose_name='Material/Technique (EN)'),
        ),
    ]
