# Generated by Django 4.2.16 on 2024-11-12 22:38

import artworks.models
import artworks.validators
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0100_alter_keyword_name_alter_keyword_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image_original',
            field=versatileimagefield.fields.VersatileImageField(max_length=255, upload_to=artworks.models.get_path_to_original_file, validators=[artworks.validators.validate_image_original], verbose_name='Original Image'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
