# Generated by Django 4.2.16 on 2024-11-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0101_alter_artwork_image_original_alter_artwork_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Name (DE)'),
        ),
    ]
