# Generated by Django 4.2.16 on 2024-11-13 14:21

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0101_alter_artwork_image_original_alter_artwork_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='synonyms',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None, verbose_name='Synonyms'),
        ),
        migrations.AlterField(
            model_name='person',
            name='synonyms',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None, verbose_name='Synonyms'),
        ),
    ]
