# Generated by Django 4.2.16 on 2024-11-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0103_alter_keyword_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name (DE)'),
        ),
    ]
