# Generated by Django 4.2.16 on 2024-11-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0104_alter_keyword_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artists',
            field=models.ManyToManyField(related_name='artworks_artists', to='artworks.person', verbose_name='Artists'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='authors',
            field=models.ManyToManyField(related_name='artworks_authors', to='artworks.person', verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='graphic_designers',
            field=models.ManyToManyField(related_name='artworks_graphic_designers', to='artworks.person', verbose_name='Graphic designers'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='photographers',
            field=models.ManyToManyField(related_name='artworks_photographers', to='artworks.person', verbose_name='Photographers'),
        ),
    ]
