# Generated by Django 4.2.16 on 2024-11-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0105_alter_artwork_artists_alter_artwork_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='keywords',
            field=models.ManyToManyField(related_name='artworks', to='artworks.keyword', verbose_name='Keywords'),
        ),
    ]
