# Generated by Django 4.2.16 on 2024-12-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0109_alter_artwork_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discriminatoryterm',
            name='term',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
