# Generated by Django 4.2.16 on 2025-12-12 12:11

import artworks.models
import artworks.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0110_alter_discriminatoryterm_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image_fullsize',
            field=models.ImageField(blank=True, max_length=255, upload_to=artworks.models.get_path_to_image_fullsize, verbose_name='Fullsize Image'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image_original',
            field=models.ImageField(max_length=255, upload_to=artworks.models.get_path_to_original_file, validators=[artworks.validators.validate_image_original], verbose_name='Original Image'),
        ),
    ]
