# Generated by Django 4.2.16 on 2024-11-08 13:17

from django.contrib.auth.management import create_permissions
from django.db import migrations


def add_permissions(apps, schema_editor):
    # create permissions
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    editors = Group.objects.get(name='editor')
    permission = Permission.objects.get(codename='change_text')

    editors.permissions.add(permission)

def remove_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    editors = Group.objects.get(name='editor')
    permission = Permission.objects.get(codename='change_text')

    editors.permissions.remove(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0037_auto_20190312_1049'),
        ('texts', '0003_alter_text_options'),
    ]

    operations = [
        migrations.RunPython(add_permissions, remove_permissions),
    ]
